config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"

  get '/clinic-team', to: 'welcome#clinic_team'
  get '/contact-us', to: 'welcome#contact_us'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def clinic_team
    end

    def contact_us
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_journey.html.erb
<div id="comp-kmwiqtqc" class="_1Q9if" data-testid="richTextElement">
	<h3 class="font_3" style="font-size:23px; text-align:center;">
		<span style="font-size:23px;">
			<span style="font-style:normal;">Begin Your Journey With Us</span>
		</span>	
	</h3>
</div>
	
<div id="comp-kmxxqp80" class="_1Q9if" data-testid="richTextElement">
	<h3 class="font_3" style="font-size:18px; text-align:center;">
		<span style="text-decoration:underline;">
			<a href="#" target="_self">
				<span style="font-size:18px;">
					<span style="font-style:normal;">Fetal Scanning & Procedures</span>
				</span>
			</a>
		</span>
	</h3>
</div>
	
<div id="comp-kmwlyrn6" class="fOSzc _2S73V">
	<a data-testid="linkElement" href="#" target="_self" class="_1PW5Q">
		<wix-image id="img_comp-kmwlyrn6" class="_1-6YJ _3p9ul" data-bg-effect-name="" data-image-zoomed="" data-has-ssr-src="true">
      <%= image_tag "fetal_scan.jpg", style: "width:260px;height:310px;object-fit:cover;object-position:50% 50%" %>                          
		</wix-image>
	</a>
</div>

<div id="comp-kn6mchr3" class="_1Q9if" data-testid="richTextElement">
  <p class="font_8" style="font-size:16px; text-align:center;">
    <span style="font-size:16px;">
      <span style="font-family:libre baskerville,serif;">
        ● Viability Scan <br/>
        ● 11-13 Week Scan <br/>
        ● Anomaly Scan <br/>
        ● Cardiac Scan <br/>
        ● Growth & Wellbeing Scan
      </span>
	  </span>
  </p>
</div>
	
<div id="comp-kmxxpoza" class="_1Q9if" data-testid="richTextElement">
	<h3 class="font_3" style="font-size:18px; text-align:center;">
		<span style="text-decoration:underline;">
			<a href="This Centre specializes in performing ultrasound scans during various stages of pregnancy and the guidelines laid out by the Fetal Medicine Foundation, UK, world pioneers in Fetal Medicine are strictly adhered to. All scans are performed by an FMF accredited operator and are accompanied with informative and sensitive counselling" target="_self">
				<span style="font-size:18px;">
					<span style="font-style:normal;">Invasive Testing</span>
				</span>
			</a>
		</span>
	</h3>
</div>
	
<div id="comp-kmwiw3ck" class="fOSzc _2S73V">
	<a data-testid="linkElement" href="#" target="_self" class="_1PW5Q">
		<wix-image id="img_comp-kmwiw3ck" class="_1-6YJ _3p9ul"  data-bg-effect-name="" data-image-zoomed="" data-has-ssr-src="true">
    <%= image_tag "invsive_testing.jpg", style: "width:260px;height:310px;object-fit:cover;object-position:50% 50%" %>                          
		</wix-image>
	</a>
</div>
	
<div id="comp-kmxxunqd" class="_1Q9if" data-testid="richTextElement">
<p class="font_8" style="font-size:16px; text-align:center;">
<span style="font-size:16px;">
  <span style="font-family:libre baskerville,serif;">
				
  ● CVS – Chorion Villus Sampling <br/>
  ● Amniocentesis <br/>
  ● Fetal Reduction </span>
		</span>
    </p>
</div>
		
<div id="comp-kmxxu5ua" class="_1Q9if" data-testid="richTextElement">
  <h3 class="font_3" style="font-size:18px; text-align:center;">
    <span style="text-decoration:underline;">
      <a href="#" target="_self">
        <span style="font-size:18px;">
          <span style="font-style:normal;">Genetic Services</span>
        </span>
      </a>
    </span>
  </h3>
</div>

<div id="comp-kmwlz3t7" class="fOSzc _2S73V">
  <a data-testid="linkElement" href="#" target="_self" class="_1PW5Q">
    <wix-image id="img_comp-kmwlz3t7" class="_1-6YJ _3p9ul" data-bg-effect-name="" data-image-zoomed="" data-has-ssr-src="true">
    <%= image_tag "genetic_services.jpg", style: "width:260px;height:310px;object-fit:cover;object-position:50% 50%" %>                          
    </wix-image>
  </a>
</div>

<div id="comp-kn6mfyrl" class="_1Q9if" data-testid="richTextElement">
<p class="font_8" style="font-size:16px; text-align:center;">
<span style="font-size:16px;">
  <span style="font-family:libre baskerville,serif;">
				
  ● Comprehensive genetic counselling <br/>
  ● Diagnosis of chromosomal, DNA & Metabolic Disorders <br/>
  ● Specialized tests including FISH for Aneuploidy, Micro-deletion Syndromes <br/>
  ● DNA tests for Single Gene Disorders <br/>
  ● Tests for inherited metabolic disorders</span>
		</span>
    </p>
</div>


<div id="comp-koeqmi7x" class="_3VCpz"></div>

app/views/application/_nav.html.erb
<wix-dropdown-menu id="comp-iiyocj9v" class="_1oZ90 _3SSUZ hidden-during-prewarmup" dir="ltr" data-stretch-buttons-to-menu-width="true" data-same-width-buttons="false" data-num-items="5" data-menuborder-y="0" data-menubtn-border="0" data-ribbon-els="0" data-label-pad="0" data-ribbon-extra="0" data-dropalign="center">
  <nav class="l76As" id="comp-iiyocj9vnavContainer" aria-label="Site">
    <ul class="_2MHbW" id="comp-iiyocj9vitemsContainer" style="text-align:center" data-marginallchildren="true"><li id="comp-iiyocj9v0" data-direction="ltr" data-listposition="left" data-data-id="bmi23nr" data-state="menu selected  link" data-index="0" class="Y5j6d _3KF65">
        <a data-testid="linkElement" href=<%= root_url%> target="_self" class="_2DUrw" aria-haspopup="false" aria-describedby="comp-iiyocj9vnavContainer-hiddenA11ySubMenuIndication">
          <div class="_1u8sp">
            <div class="" style="text-align:center">
              <p class="_1zyfI" style="text-align:center" id="comp-iiyocj9v0label">Home</p>
            </div>
          </div>
        </a>
        
        <!--ul aria-hidden="true" style="display:none">
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Testimonials</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Fees</a>
          </li>
        </ul-->
      </li><li id="comp-iiyocj9v1" data-direction="ltr" data-listposition="center" data-data-id="dataItem-kmuy9yev" data-state="menu false  link" data-index="1" class="Y5j6d _3KF65">
        <a data-testid="linkElement" href="#" target="_self" class="_2DUrw" aria-haspopup="false" aria-describedby="comp-iiyocj9vnavContainer-hiddenA11ySubMenuIndication">
          <div class="_1u8sp">
            <div class="" style="text-align:center">
              <p class="_1zyfI" style="text-align:center" id="comp-iiyocj9v1label">Ultrasound Scans</p>
            </div>
          </div>
        </a>
        
        <!--ul aria-hidden="true" style="display:none">
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Early Pregnancy Scan</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Nuchal Scan</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Early Anatomy Scan</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Anomaly Scan</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Cervical Length Scan</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Fetal Heart Scan</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Growth Scan</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">3D and 4D Scan</a>
          </li>
        </ul-->
      </li><li id="comp-iiyocj9v2" data-direction="ltr" data-listposition="center" data-data-id="dataItem-kmuzhvxc" data-state="menu false  link" data-index="2" class="Y5j6d _3KF65">
        <a data-testid="linkElement" href="#" target="_self" class="_2DUrw" aria-haspopup="false">
          <div class="_1u8sp">
            <div class="" style="text-align:center">
              <p class="_1zyfI" style="text-align:center" id="comp-iiyocj9v2label">Harmony Test</p>
            </div>
          </div>
        </a>
      </li><li id="comp-iiyocj9v3" data-direction="ltr" data-listposition="center" data-data-id="dataItem-kqc8b8eh" data-state="menu false  link" data-index="3" class="Y5j6d _3KF65">
        <a data-testid="linkElement" href=<%= clinic_team_path %> target="_self" class="_2DUrw" aria-haspopup="false" aria-describedby="comp-iiyocj9vnavContainer-hiddenA11ySubMenuIndication">
          <div class="_1u8sp">
            <div class="" style="text-align:center">
              <p class="_1zyfI" style="text-align:center" id="comp-iiyocj9v3label">Clinic Team</p>
            </div>
          </div>
        </a> 
        <!--ul aria-hidden="true" style="display:none">
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Professor Akolekar</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Ashleigh Paige</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Milena Wezgowiec</a>
          </li>
        </ul-->
      </li><li id="comp-iiyocj9v4" data-direction="ltr" data-listposition="right" data-data-id="dataItem-ij44ja9o" data-state="menu false  link" data-index="4" class="Y5j6d _3KF65">
        <a data-testid="linkElement" href=<%= contact_us_path %> target="_self" class="_2DUrw" aria-haspopup="false" aria-describedby="comp-iiyocj9vnavContainer-hiddenA11ySubMenuIndication">
          <div class="_1u8sp">
            <div class="" style="text-align:center">
              <p class="_1zyfI" style="text-align:center" id="comp-iiyocj9v4label">Contact Us</p>
            </div>
          </div>
        </a>
        <ul aria-hidden="true" style="display:none">
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Pregnancy Clinic Epsom</a>
          </li>
          <li>
            <a data-testid="linkElement" href="#" target="_self" class="" aria-haspopup="false" tabindex="-1">Pregnancy Clinic Sevenoaks</a>
          </li>
        </ul>
      </li><li id="comp-iiyocj9v__more__" data-direction="ltr" data-listposition="right" data-state="menu false  header" data-index="__more__" data-dropdown="false" class="_2nffT _3KF65">
        <div data-testid="linkElement" class="_2DUrw" tabindex="0" aria-haspopup="false">
          <div class="_1u8sp">
            <div class="" style="text-align:center">
              <p class="_1zyfI" style="text-align:center" id="comp-iiyocj9v__more__label">More...</p>
            </div>
          </div>
        </div>
      </li></ul>
      
    <div class="_2vbYi" id="comp-iiyocj9vdropWrapper" data-dropalign="center" data-dropdown-shown="false">
      <ul class="_1mmDc" id="comp-iiyocj9vmoreContainer"></ul>
    </div>
    <div style="display:none" id="comp-iiyocj9vnavContainer-hiddenA11ySubMenuIndication">Use tab to navigate through the menu items.</div
  </nav>
</wix-dropdown-menu>

app/views/application/index.html.erb
<div id="SITE_CONTAINER">
  <div id="main_MF">
    <div id="SCROLL_TO_TOP" class="qhwIj ignore-focus" tabindex="-1" role="region" aria-label="top of page"> </div>

    <div id="BACKGROUND_GROUP">
      <div id="BACKGROUND_GROUP_TRANSITION_GROUP">
        <div id="pageBackground_c1dmp" data-media-height-override-type="" data-media-position-override="false" class="_2v3yk">
          <div id="bgLayers_pageBackground_c1dmp" data-hook="bgLayers" class="_3wnIc">
            <div data-testid="colorUnderlay" class="_3KzuS _3SQN-"></div>
            <div id="bgMedia_pageBackground_c1dmp" class="_2GUhU"></div>
            <div data-testid="bgOverlay" class="_1eCSh"></div>
          </div>
        </div>
      </div>
    </div>

    <div id="site-root">
      <div id="masterPage" class="mesh-layout">
        <%= render "header" %>

        <main id="PAGES_CONTAINER" tabindex="-1">
          <div id="SITE_PAGES">
            <div id="SITE_PAGES_TRANSITION_GROUP" class="_2YGAo">
              <div id="c1dmp" class="_2hsyZ Em8dO">
                <div class="_1ZNMx" data-testid="page-bg"></div>
                <div class="l4R05">
                  <div id="Containerc1dmp" class="_1KV2M">
                    <div data-mesh-id="Containerc1dmpinlineContent" data-testid="inline-content" class="">
                      <div data-mesh-id="Containerc1dmpinlineContent-gridContainer" data-testid="mesh-container-content">
                        <div id="comp-ikma4r17" class="_2UdPt"></div>
                        <div id="comp-jf1l87or" style="display:none"></div>
                        <div id="comp-kmuwm8dg" class="XUUsC">
                          <div data-testid="linkElement" class="xQ_iF">
                            <wix-image id="img_comp-kmuwm8dg" class="_1-6YJ _1Fe8-" data-bg-effect-name="" data-image-zoomed="" data-has-ssr-src="true">
                              <%= image_tag "main.jpg", style: "width:980px;height:500px;object-fit:cover;object-position:50% 50%" %>
                            </wix-image>
                          </div>
                        </div>
                        
                        <div id="comp-klwsnbv5" class="_1Q9if" data-testid="richTextElement">
                          <h3 class="font_3" style="font-size:24px; text-align:center;">
                            <span style="font-size:24px;">
                              <span style="font-style:normal;">Welcome to The AAROHAN&nbsp;</span>
                            </span>
                          </h3>
                        </div>
                        
                        <section id="comp-klwsnbrn" class="_3d64y">
                          <div id="bgLayers_comp-klwsnbrn" data-hook="bgLayers" class="_3wnIc">
                            <div data-testid="colorUnderlay" class="_3KzuS _3SQN-"></div>
                            <div id="bgMedia_comp-klwsnbrn" class="_2GUhU"></div>
                          </div>
                          
                          <div data-testid="columns" class="_1uldx">
                            <div id="comp-klwsnbv3" class="_1vNJf">
                              <div id="bgLayers_comp-klwsnbv3" data-hook="bgLayers" class="_3wnIc">
                                <div data-testid="colorUnderlay" class="_3KzuS _3SQN-"></div>
                                <div id="bgMedia_comp-klwsnbv3" class="_2GUhU"></div>
                              </div>
                              
                              <div data-mesh-id="comp-klwsnbv3inlineContent" data-testid="inline-content" class="">
                                <div data-mesh-id="comp-klwsnbv3inlineContent-gridContainer" data-testid="mesh-container-content">
                                  <div id="comp-klwsnbvb" class="_1Q9if" data-testid="richTextElement">
                                    <h2 class="font_2" style="line-height:0.6em; text-align:center; font-size:35px;">
                                      <span style="font-family:libre baskerville,serif; font-size:16px; letter-spacing:0em;">Aarohan Fetal Medicine Centre was set up with the aim of providing the best in prenatal care, diagnosis and treatment. Prevention is the first aspect of reducing the burden of birth defects. Diagnosis of these problems within the womb and offering fetal therapy when possible is an important aspect of care. Despite the best of efforts, there will be children born with problems; some of which may be correctable and some not. It is with this three pronged philosophy that the Aarohan Fetal Medicine Center was born: Preventive, Curative and Supportive care of the Fetus.&nbsp;</span>
                                      
                                    </h2>

                                    <h2 class="font_2" style="line-height:0.6em; text-align:center; font-size:35px;">
                                      <span style="font-family:libre baskerville,serif; font-size:16px; letter-spacing:0em;">
                                        <span class="wixGuard">​</span>
                                      </span>
                                    </h2>

                                    <h2 class="font_2" style="line-height:0.6em; text-align:center; font-size:35px;">
                                      <span style="font-family:libre baskerville,serif; font-size:16px; letter-spacing:0em;">This Centre specializes in performing ultrasound scans during various stages of pregnancy and the guidelines laid out by the Fetal Medicine Foundation, UK, world pioneers in Fetal Medicine are strictly adhered to. All scans are performed by an FMF accredited operator and are accompanied with informative and sensitive counselling </span>
                                    </h2>

                                    <h2 class="font_2" style="font-size:16px; line-height:0.6em; text-align:center;">
                                      <span class="wixGuard">​</span>
                                    </h2>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </section>
                        
                        <div id="comp-kmwibh3r" class="_3VCpz"></div>
                        
                        <div id="comp-kmwi7at7" class="fOSzc">
                          <div data-testid="linkElement" class="_1PW5Q">
                            <wix-image id="img_comp-kmwi7at7" class="_1-6YJ _3p9ul" data-bg-effect-name="" data-image-zoomed="" data-has-ssr-src="true">
                              <%= image_tag "gynic.jpg", style: "width:430px;height:247px;object-fit:cover;object-position:50% 50%" %>                          
                            </wix-image>
                          </div>
                        </div>
                        
                        <div id="comp-kmwi7lvp" class="_1Q9if" data-testid="richTextElement">
                          <h3 class="font_3" style="font-size:23px; text-align:center;">
                            <span style="font-size:23px;">
                              <span style="font-style:normal;">Dr. Preeti Parekh Tomar</span>
                            </span>
                          </h3>
                        </div>
                        
                        <div id="comp-kmytj3v8" class="_1Q9if" data-testid="richTextElement">
                          <h2 class="font_2" style="line-height:0.6em; text-align:center; font-size:35px;">
                            <span style="font-family:libre baskerville,serif; font-size:16px; letter-spacing:0em;">
                            Fetal Medicine Specialist <br/>
                            Clinical Director at Aarohan Fetal Medicine Centre, <br/>
                            Indore Former: Consultant Fetal Medicine Centre @ CHL Hospitals, Indore</span>
                          </h2>

                          <h2 class="font_2" style="font-size:16px; line-height:0.6em; text-align:center;">&nbsp;</h2>

                          <h2 class="font_2" style="font-size:16px; line-height:0.6em; text-align:center;">
                            <span class="wixGuard">​</span>
                          </h2>
                        </div>
                        
                        <div id="comp-kmytslth" aria-disabled="false" class="_2UgQw">
                          <a data-testid="linkElement" href=<%= clinic_team_url%> target="_self" class="_1fbEI" aria-disabled="false">
                            <span class="_1Qjd7">Read on</span>
                          </a>
                        </div>
                        
                        <div id="comp-kmwidauy" class="_3VCpz"></div>

                        <%= render "journey" %>

                        <div id="comp-koeqmxgd" class="_1Q9if" data-testid="richTextElement">
                          <h3 class="font_3" style="font-size:23px; text-align:center;">
                            <span style="font-size:23px;">
                              <span style="font-style:normal;">What Our Patients Say</span>
                            </span>
                          </h3>
                        </div>
                        
                        <div id="comp-koeqvqqx" class="_1Q9if" data-testid="richTextElement">
                          <p class="font_8" style="font-size:16px; text-align:center;">
                            <span class="color_14">
                              <span style="font-style:italic;">
                                <span style="font-size:16px;">
                                  <span style="font-family:libre baskerville,serif;">I cannot recommend the clinic highly enough. From my first phone call, I was made to feel at ease in a situation we didn&rsquo;t think we would find ourselves in. I called at 12pm on a Monday and was seen that evening at 6pm. We had the results back that Friday. Professor Akolekar &amp; his team were very professional at all times but made an unexpected situation stress free and we will definitely return if needed in the future.</span>
                                </span>
                              </span>
                            </span>
                          </p>

                          <p class="font_8" style="font-size:16px; text-align:center;">
                            <span style="font-size:16px;">
                              <span style="font-family:libre baskerville,serif;">-Emma D</span>
                            </span>
                          </p>
                        </div>
                        
                        <div id="comp-koeqxgym" aria-disabled="false" class="_2UgQw">
                          <a data-testid="linkElement" href="#" target="_self" class="_1fbEI" aria-disabled="false">
                            <span class="_1Qjd7">Read more testimonials</span>
                          </a>
                        </div>
                        
                        <div data-mesh-id="Containerc1dmpinlineContent-wedge-19"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
                      
        <div id="soapAfterPagesContainer" class="page-without-sosp">
          <div data-mesh-id="soapAfterPagesContainerinlineContent" data-testid="inline-content" class="">
            <div data-mesh-id="soapAfterPagesContainerinlineContent-gridContainer" data-testid="mesh-container-content">
              <div id="comp-jn4djzy1" style="display:none"></div>
            </div>
          </div>
        </div>

        <%= render "footer"%>
    </div>
  </div>
</div>

app/views/layouts/_init_js.html.erb
<script type="text/javascript">
    var bodyCacheable = true;
    
    var exclusionReason = {"shouldRender":true,"forced":false};
    var ssrInfo = {"renderBodyTime":1798,"renderTimeStamp":1654325860448}
</script>




<script>window.clientSideRender = false;</script>


    <!--pageHtmlEmbeds.bodyStart start-->
    <script type="wix/htmlEmbeds" id="pageHtmlEmbeds.bodyStart start"></script>
    
    <script type="wix/htmlEmbeds" id="pageHtmlEmbeds.bodyStart end"></script>
    <!--pageHtmlEmbeds.bodyStart end-->




<script id="wix-first-paint">
    if (window.ResizeObserver &&
        (!window.PerformanceObserver || !PerformanceObserver.supportedEntryTypes || PerformanceObserver.supportedEntryTypes.indexOf('paint') === -1)) {
        new ResizeObserver(function (entries, observer) {
            entries.some(function (entry) {
                var contentRect = entry.contentRect;
                if (contentRect.width > 0 && contentRect.height > 0) {
                    requestAnimationFrame(function (now) {
                        window.wixFirstPaint = now;
                        dispatchEvent(new CustomEvent('wixFirstPaint'));
                    });
                    observer.disconnect();
                    return true;
                }
            });
        }).observe(document.body);
    }
</script>

<pages-css id="pages-css"><style id="css_masterPage">

	


</style>
<style id="css_c1dmp">
	

</style></pages-css>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arohan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header_external" %>
    <%= render "layouts/init_js" %>
    <%= yield %>
  </body>
</html>